"""empty message

Revision ID: f71001c3e24b
Revises: f3de8b7ebc0e
Create Date: 2024-01-23 21:19:02.621036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71001c3e24b'
down_revision = 'f3de8b7ebc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_address_key', type_='unique')
        batch_op.drop_constraint('user_city_key', type_='unique')
        batch_op.drop_constraint('user_state_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_state_key', ['state'])
        batch_op.create_unique_constraint('user_city_key', ['city'])
        batch_op.create_unique_constraint('user_address_key', ['address'])

    # ### end Alembic commands ###
